export const projectTabs = ['Dati progetto', 'Variabili', 'Sync', 'Immagini', 'Note'] as const
export const pinnedProjectIdsStorageKey = 'app-control-pinned-project-ids'

export const legacyDefaultSyncPrompt =
  'Sincronizza questo progetto con App Control. Controlla se esiste `.agent/app-control.json`. Se esiste, usa `projectId` e `agentKey` per caricare da App Control le variabili autorizzate del progetto. Se non esiste, chiedimi la Agent Key e guidami nel collegamento del progetto. Poi genera o aggiorna `.env`, verifica che `.env` sia in `.gitignore`, integra nel codice solo le variabili necessarie, verifica la connessione Supabase senza esporre segreti, usa GitHub solo tramite `gh` o credenziali autorizzate, prima di commit o push chiedi conferma esplicita, e non stampare token, password, service role key o DB URL nei log o nella chat.'

export const previousDefaultSyncPrompt =
  'Sincronizza questo progetto con App Control. Controlla se esiste `.agent/app-control.json`. Se esiste, usa `projectId` e `agentKey` per collegare il progetto e leggere da App Control solo i dati canonici disponibili: Dati progetto (`Nome progetto`, `Mail accesso`, `Password`, `Sviluppo in`, `Accessi piattaforme`, `Deploy con`, `Password`) e Variabili (`LINK_DEPLOY`, `GITHUB_URL`, `GITHUB_TOKEN`, `SUPABASE_URL`, `SUPABASE_ANON_KEY`, `SUPABASE_SERVICE_ROLE_KEY`, `DATABASE_URL`, `RENDER_API_KEY`). Se non esiste, chiedimi la Agent Key e guidami nel collegamento del progetto. Analizza il codice reale del repository per capire quali variabili servono davvero. Se il progetto usa Vite o altre env client-side, deriva quando necessario `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`, senza aspettarti che siano salvate come campi separati in App Control. Se uno script, template o provider richiede `SUPABASE_DB_URL`, trattala come alias di `DATABASE_URL` e generala solo quando serve. Poi genera o aggiorna `.env`, verifica che `.env` sia in `.gitignore`, integra nel codice solo le variabili necessarie, verifica la connessione Supabase senza esporre segreti, usa GitHub solo tramite `gh` o credenziali autorizzate, prima di commit o push chiedi conferma esplicita, e non stampare token, password, service key, Render API key o DB URL nei log o nella chat.'

// Versione precedente del defaultSyncPrompt (senza CLAUDE.MD / value_text): tenuta
// come legacy per essere rimpiazzata automaticamente da resolveSyncPrompt.
export const priorDefaultSyncPrompt =
  'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Recupera i dati canonici da `project_env_variables`, `project_data_fields`, `project_platform_accesses` e `projects`. Se il file `.agent/app-control.json` non esiste, informa l\'utente: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. Dopo aver recuperato i dati: genera o aggiorna `.env` con tutte le variabili del progetto; genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY); verifica che `.env`, `.mcp.json` e `.agent/` siano nel `.gitignore`; configura il remote git origin usando il token: esegui `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` sostituendo GITHUB_TOKEN con il valore reale e REPO_PATH con il path estratto da GITHUB_URL — questo garantisce che push e pull usino sempre le credenziali del progetto corretto indipendentemente dall\'account gh globale; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`; verifica le connessioni a GitHub, Supabase e Render; non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita.'

export const defaultSyncPrompt =
  'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall\'account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l\'unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l\'app in locale sulla porta 5001.'

export type ProjectTab = (typeof projectTabs)[number]
export type ProjectListSortMode = 'recent-desc' | 'name-asc' | 'name-desc'
export type ProjectSaveState = 'idle' | 'saving' | 'saved' | 'error'
