-- Genera le agent key mancanti per i 10 progetti storici creati prima della
-- generazione automatica della key (createProjectRecord). Senza una riga in
-- project_agent_keys il canale agent non funziona e il tab Sync produce un
-- .agent/app-control.json con agentKey vuoto: la sincronizzazione non parte.
--
-- Replica fedele di createProjectRecord (src/features/projects/projectRepository.ts):
--   key formato XXXXX-XXXXX-XXXXX-XXXXX, key_hash = SHA-256 hex della key,
--   key_ciphertext = key in chiaro, sync_prompt = defaultSyncPrompt corrente,
--   flag can_* come la 'Default agent key' esistente.
--
-- Additiva e idempotente: inserisce solo dove non esiste gia' una key per il
-- progetto (NOT EXISTS). Non tocca dati esistenti ne' gli 8 progetti gia' dotati di key.

-- SITECCV
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', '4D326', 'b293133aedbf1248b6a39d4e1911a85940dd817ddb00b3088dafb792204289ca', '4D326-TVV9F-96AJZ-6DD5N', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-cwl78'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- ISYAPP
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', 'EA8QU', 'd02899fb005442fe869664f940237bc3b415a0db6eb8258a3d9ecdd46c6dffc5', 'EA8QU-4YTN3-AHZTA-GFPQP', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-vzt5j'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- BADGENODE
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', 'KPZHG', 'dd1117c71fc1f2273e8b1907779c6d283b18ab987e11bc976d98f752dd2b0203', 'KPZHG-97R7H-UFXAE-9AF5V', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-d5rr9'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- APP CONTROL
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', 'YEH5S', '6bbc63d7f7a826e9bf0be439593591fe51d0d67139978559561c65c6fe01c459', 'YEH5S-D36C4-ZYZ33-FLELJ', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-fuzzr'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- WEDDING APP
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', 'BCYAE', '1889bdff30fde350f3e10dc72e5b35c30ec3a3c626e8583b06cddfbb1b5a61fb', 'BCYAE-3CAMH-EX5DT-PZH7R', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-8bg7f'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- ENOTECA ITALIANA
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', '2TEEF', '2c605467698fae6ad2d98d8f69754321e6f85b7d6bc45681d9c9dd7f4c2b0a40', '2TEEF-CGSPT-PR4TA-J74TQ', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-ajxdh'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- DIAGONALE
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', 'E9XAY', '560665389877bcfa1c2ce475d47a73ac3253483e3dec9e6909db0eef7d27d728', 'E9XAY-4HWN6-LUE9B-XYRAM', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-llqq3'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- RSVP
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', 'VZ9LA', '515b1347309fddc6857231d76245656affd8a17f6e465ec91decb44eaf57cbc6', 'VZ9LA-X8L2Z-ZR9YX-FNYVX', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-l6h2r'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- MONEY BOX
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', '825H9', '105dca5ff97367a0ab7f05a3eaf95a0c4b4e04e8decefa0953729e3a1b75a425', '825H9-T3UUC-KESQD-QVARP', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-348eh'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);

-- LAZZARO
insert into public.project_agent_keys
  (project_id, name, key_prefix, key_hash, key_ciphertext, sync_prompt,
   can_read_project, can_read_env, can_read_platform_accesses, can_read_secrets, can_prepare_git)
select p.id, 'Default agent key', 'A499P', 'e00436b44c0c7e7bb1b3fc13520364b498f275876fd93b2310af135afcf3c353', 'A499P-8B55A-B3DVT-UYMPP', 'Sincronizza questo progetto con App Control. Leggi il file `.agent/app-control.json` nella root del progetto. Se esiste, usa `projectId`, `agentKey`, `appControlSupabaseUrl` e `appControlSupabaseAnonKey` per leggere da App Control via Supabase REST inviando gli header `x-app-control-project-id` e `x-app-control-agent-key`. Se il file `.agent/app-control.json` non esiste, fermati: AZIONE ORA: apri App Control, vai sul progetto, clicca il tab Sync e copia il contenuto di `.agent/app-control.json`, poi incollalo qui. (1) Aggiungi `.env`, `.mcp.json` e `.agent/` al `.gitignore`. (2) Scarica il prompt `CLAUDE.MD` dalla tabella `prompts` di App Control e scrivilo come `CLAUDE.md` nella root del progetto, poi applicane le regole al 100%. (3) Recupera i dati canonici da `project_env_variables` (colonna valore: `value_text`, non `value`), `project_data_fields`, `project_platform_accesses` e `projects`. (4) Genera o aggiorna `.env` con tutte le variabili del progetto; se il progetto usa Vite, deriva `VITE_SUPABASE_URL` da `SUPABASE_URL` e `VITE_SUPABASE_ANON_KEY` da `SUPABASE_ANON_KEY`; se serve `SUPABASE_DB_URL` trattala come alias di `DATABASE_URL`. (5) Genera `.mcp.json` con i server MCP GitHub (usando GITHUB_TOKEN) e Supabase (usando SUPABASE_URL e SUPABASE_SERVICE_ROLE_KEY). (6) Configura il remote git origin col token: `git remote set-url origin https://GITHUB_TOKEN@github.com/REPO_PATH.git` (GITHUB_TOKEN reale, REPO_PATH estratto da GITHUB_URL), cosi push e pull usano sempre le credenziali del progetto, indipendentemente dall''account gh globale. (7) Quando durante lo sviluppo generi nuove variabili o segreti, riscrivili in App Control SOLO nella tabella `project_env_variables` del progetto (l''unica scrivibile dal canale agent): usa i nomi canonici e la colonna `value_text`. (8) DUE LINK DI DEPLOY: rileva dal progetto reale entrambi i link e scrivili/aggiornali in `project_env_variables` (`value_text`). `LINK_DEPLOY` = URL pubblico lato utente. `LINK_DEPLOY ADMIN` = URL reale dell''area admin di QUESTO progetto: il percorso o sottodominio cambia da progetto a progetto, quindi ricavalo dal codice e dalla configurazione reali (route admin, config di deploy Render, README) e NON assumere un suffisso fisso. Se i valori gia presenti in App Control non corrispondono ai link reali, correggili; mantieni entrambi aggiornati a ogni variazione del deploy. (9) Verifica le connessioni a GitHub, Supabase e Render in sola lettura, senza dichiararle ok senza prova. Non stampare mai token, password, chiavi o segreti in chat o log; prima di qualsiasi commit o push chiedi conferma esplicita. Al termine, se previsto, avvia l''app in locale sulla porta 5001.',
       true, true, false, false, true
from public.projects p
where p.agent_project_id = 'prj-3ywrl'
  and not exists (select 1 from public.project_agent_keys k where k.project_id = p.id);
